#############################################################################
# Makefile for building: RecruitmentManager
# Generated by qmake (3.1) (Qt 5.15.19)
# Project:  Project.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Project.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -Ithird_party -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = RecruitmentManager1.0.0
DISTDIR = /home/olivier/personal/MAS/project/.tmp/RecruitmentManager1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -pipe -O2 -std=gnu++1z -flto=8 -fno-fat-lto-objects -fuse-linker-plugin -fPIC
LIBS          = $(SUBLIBS) /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Sql.so /usr/lib/libQt5Core.so -lGL -lpthread   
AR            = gcc-ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		models/Candidate.cpp \
		models/Company.cpp \
		models/Recruiter.cpp \
		models/JobPosting.cpp \
		models/Application.cpp \
		models/Interview.cpp \
		models/CVDocument.cpp \
		models/CVSection.cpp \
		models/WorkExperience.cpp \
		models/Education.cpp \
		models/VolunteerWork.cpp \
		models/Skill.cpp \
		models/TechnicalSkillRole.cpp \
		models/SoftSkillRole.cpp \
		models/MediaAttachment.cpp \
		models/RatableItem.cpp \
		models/PortfolioEntry.cpp \
		models/AppliedState.cpp \
		models/InterviewingState.cpp \
		models/HiredState.cpp \
		models/RejectedState.cpp \
		repositories/Database.cpp \
		repositories/CandidateRepository.cpp \
		repositories/CompanyRepository.cpp \
		repositories/RecruiterRepository.cpp \
		repositories/JobPostingRepository.cpp \
		repositories/ApplicationRepository.cpp \
		repositories/InterviewRepository.cpp \
		views/MainWindow.cpp \
		dialogs/NewCandidateDialog.cpp \
		dialogs/NewJobPostingDialog.cpp \
		dialogs/ApplyDialog.cpp \
		dialogs/AdvanceStatusDialog.cpp moc_MainWindow.cpp
OBJECTS       = main.o \
		Candidate.o \
		Company.o \
		Recruiter.o \
		JobPosting.o \
		Application.o \
		Interview.o \
		CVDocument.o \
		CVSection.o \
		WorkExperience.o \
		Education.o \
		VolunteerWork.o \
		Skill.o \
		TechnicalSkillRole.o \
		SoftSkillRole.o \
		MediaAttachment.o \
		RatableItem.o \
		PortfolioEntry.o \
		AppliedState.o \
		InterviewingState.o \
		HiredState.o \
		RejectedState.o \
		Database.o \
		CandidateRepository.o \
		CompanyRepository.o \
		RecruiterRepository.o \
		JobPostingRepository.o \
		ApplicationRepository.o \
		InterviewRepository.o \
		MainWindow.o \
		NewCandidateDialog.o \
		NewJobPostingDialog.o \
		ApplyDialog.o \
		AdvanceStatusDialog.o \
		moc_MainWindow.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		Project.pro models/Candidate.h \
		models/Company.h \
		models/Recruiter.h \
		models/JobPosting.h \
		models/Application.h \
		models/Interview.h \
		models/CVDocument.h \
		models/CVSection.h \
		models/WorkExperience.h \
		models/Education.h \
		models/VolunteerWork.h \
		models/Skill.h \
		models/ITechnical.h \
		models/ISoft.h \
		models/TechnicalSkillRole.h \
		models/SoftSkillRole.h \
		models/MediaAttachment.h \
		models/RatableItem.h \
		models/PortfolioEntry.h \
		models/ApplicationState.h \
		models/AppliedState.h \
		models/InterviewingState.h \
		models/HiredState.h \
		models/RejectedState.h \
		repositories/Database.h \
		repositories/Records.h \
		repositories/CandidateRepository.h \
		repositories/CompanyRepository.h \
		repositories/RecruiterRepository.h \
		repositories/JobPostingRepository.h \
		repositories/ApplicationRepository.h \
		repositories/InterviewRepository.h \
		views/MainWindow.h \
		dialogs/NewCandidateDialog.h \
		dialogs/NewJobPostingDialog.h \
		dialogs/ApplyDialog.h \
		dialogs/AdvanceStatusDialog.h main.cpp \
		models/Candidate.cpp \
		models/Company.cpp \
		models/Recruiter.cpp \
		models/JobPosting.cpp \
		models/Application.cpp \
		models/Interview.cpp \
		models/CVDocument.cpp \
		models/CVSection.cpp \
		models/WorkExperience.cpp \
		models/Education.cpp \
		models/VolunteerWork.cpp \
		models/Skill.cpp \
		models/TechnicalSkillRole.cpp \
		models/SoftSkillRole.cpp \
		models/MediaAttachment.cpp \
		models/RatableItem.cpp \
		models/PortfolioEntry.cpp \
		models/AppliedState.cpp \
		models/InterviewingState.cpp \
		models/HiredState.cpp \
		models/RejectedState.cpp \
		repositories/Database.cpp \
		repositories/CandidateRepository.cpp \
		repositories/CompanyRepository.cpp \
		repositories/RecruiterRepository.cpp \
		repositories/JobPostingRepository.cpp \
		repositories/ApplicationRepository.cpp \
		repositories/InterviewRepository.cpp \
		views/MainWindow.cpp \
		dialogs/NewCandidateDialog.cpp \
		dialogs/NewJobPostingDialog.cpp \
		dialogs/ApplyDialog.cpp \
		dialogs/AdvanceStatusDialog.cpp
QMAKE_TARGET  = RecruitmentManager
DESTDIR       = 
TARGET        = RecruitmentManager


first: all
####### Build rules

RecruitmentManager:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Project.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		Project.pro
	$(QMAKE) -o Makefile Project.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/link_ltcg.prf:
/usr/lib/qt/mkspecs/features/ltcg.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources_functions.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
Project.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Project.pro

qmake_all: FORCE


all: Makefile RecruitmentManager

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents models/Candidate.h models/Company.h models/Recruiter.h models/JobPosting.h models/Application.h models/Interview.h models/CVDocument.h models/CVSection.h models/WorkExperience.h models/Education.h models/VolunteerWork.h models/Skill.h models/ITechnical.h models/ISoft.h models/TechnicalSkillRole.h models/SoftSkillRole.h models/MediaAttachment.h models/RatableItem.h models/PortfolioEntry.h models/ApplicationState.h models/AppliedState.h models/InterviewingState.h models/HiredState.h models/RejectedState.h repositories/Database.h repositories/Records.h repositories/CandidateRepository.h repositories/CompanyRepository.h repositories/RecruiterRepository.h repositories/JobPostingRepository.h repositories/ApplicationRepository.h repositories/InterviewRepository.h views/MainWindow.h dialogs/NewCandidateDialog.h dialogs/NewJobPostingDialog.h dialogs/ApplyDialog.h dialogs/AdvanceStatusDialog.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp models/Candidate.cpp models/Company.cpp models/Recruiter.cpp models/JobPosting.cpp models/Application.cpp models/Interview.cpp models/CVDocument.cpp models/CVSection.cpp models/WorkExperience.cpp models/Education.cpp models/VolunteerWork.cpp models/Skill.cpp models/TechnicalSkillRole.cpp models/SoftSkillRole.cpp models/MediaAttachment.cpp models/RatableItem.cpp models/PortfolioEntry.cpp models/AppliedState.cpp models/InterviewingState.cpp models/HiredState.cpp models/RejectedState.cpp repositories/Database.cpp repositories/CandidateRepository.cpp repositories/CompanyRepository.cpp repositories/RecruiterRepository.cpp repositories/JobPostingRepository.cpp repositories/ApplicationRepository.cpp repositories/InterviewRepository.cpp views/MainWindow.cpp dialogs/NewCandidateDialog.cpp dialogs/NewJobPostingDialog.cpp dialogs/ApplyDialog.cpp dialogs/AdvanceStatusDialog.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -flto -fno-fat-lto-objects -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp
moc_MainWindow.cpp: views/MainWindow.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/olivier/personal/MAS/project/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/olivier/personal/MAS/project -I/home/olivier/personal/MAS/project -I/home/olivier/personal/MAS/project/third_party -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtSql -I/usr/include/qt/QtCore -I/usr/include/c++/16.1.1 -I/usr/include/c++/16.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/16.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16.1.1/include -I/usr/local/include -I/usr/include views/MainWindow.h -o moc_MainWindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp views/MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Candidate.o: models/Candidate.cpp models/Candidate.h \
		models/ApplicationState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Candidate.o models/Candidate.cpp

Company.o: models/Company.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Company.o models/Company.cpp

Recruiter.o: models/Recruiter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Recruiter.o models/Recruiter.cpp

JobPosting.o: models/JobPosting.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JobPosting.o models/JobPosting.cpp

Application.o: models/Application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Application.o models/Application.cpp

Interview.o: models/Interview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Interview.o models/Interview.cpp

CVDocument.o: models/CVDocument.cpp models/CVDocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CVDocument.o models/CVDocument.cpp

CVSection.o: models/CVSection.cpp models/CVSection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CVSection.o models/CVSection.cpp

WorkExperience.o: models/WorkExperience.cpp models/WorkExperience.h \
		models/CVSection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WorkExperience.o models/WorkExperience.cpp

Education.o: models/Education.cpp models/Education.h \
		models/CVSection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Education.o models/Education.cpp

VolunteerWork.o: models/VolunteerWork.cpp models/VolunteerWork.h \
		models/CVSection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VolunteerWork.o models/VolunteerWork.cpp

Skill.o: models/Skill.cpp models/Skill.h \
		models/ITechnical.h \
		models/ISoft.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Skill.o models/Skill.cpp

TechnicalSkillRole.o: models/TechnicalSkillRole.cpp models/TechnicalSkillRole.h \
		models/ITechnical.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TechnicalSkillRole.o models/TechnicalSkillRole.cpp

SoftSkillRole.o: models/SoftSkillRole.cpp models/SoftSkillRole.h \
		models/ISoft.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoftSkillRole.o models/SoftSkillRole.cpp

MediaAttachment.o: models/MediaAttachment.cpp models/MediaAttachment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MediaAttachment.o models/MediaAttachment.cpp

RatableItem.o: models/RatableItem.cpp models/RatableItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RatableItem.o models/RatableItem.cpp

PortfolioEntry.o: models/PortfolioEntry.cpp models/PortfolioEntry.h \
		models/MediaAttachment.h \
		models/RatableItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PortfolioEntry.o models/PortfolioEntry.cpp

AppliedState.o: models/AppliedState.cpp models/AppliedState.h \
		models/ApplicationState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AppliedState.o models/AppliedState.cpp

InterviewingState.o: models/InterviewingState.cpp models/InterviewingState.h \
		models/ApplicationState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InterviewingState.o models/InterviewingState.cpp

HiredState.o: models/HiredState.cpp models/HiredState.h \
		models/ApplicationState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HiredState.o models/HiredState.cpp

RejectedState.o: models/RejectedState.cpp models/RejectedState.h \
		models/ApplicationState.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RejectedState.o models/RejectedState.cpp

Database.o: repositories/Database.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Database.o repositories/Database.cpp

CandidateRepository.o: repositories/CandidateRepository.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CandidateRepository.o repositories/CandidateRepository.cpp

CompanyRepository.o: repositories/CompanyRepository.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CompanyRepository.o repositories/CompanyRepository.cpp

RecruiterRepository.o: repositories/RecruiterRepository.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RecruiterRepository.o repositories/RecruiterRepository.cpp

JobPostingRepository.o: repositories/JobPostingRepository.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JobPostingRepository.o repositories/JobPostingRepository.cpp

ApplicationRepository.o: repositories/ApplicationRepository.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ApplicationRepository.o repositories/ApplicationRepository.cpp

InterviewRepository.o: repositories/InterviewRepository.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InterviewRepository.o repositories/InterviewRepository.cpp

MainWindow.o: views/MainWindow.cpp views/MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o views/MainWindow.cpp

NewCandidateDialog.o: dialogs/NewCandidateDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NewCandidateDialog.o dialogs/NewCandidateDialog.cpp

NewJobPostingDialog.o: dialogs/NewJobPostingDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NewJobPostingDialog.o dialogs/NewJobPostingDialog.cpp

ApplyDialog.o: dialogs/ApplyDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ApplyDialog.o dialogs/ApplyDialog.cpp

AdvanceStatusDialog.o: dialogs/AdvanceStatusDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AdvanceStatusDialog.o dialogs/AdvanceStatusDialog.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

